### PR TITLE
builtin parse handlers

### PR DESCRIPTION
**Pull request by ParallelTask**

### CODE REVIEW

**Comment by TheWillG** [comment]
I have tested using Postman and it works good in that I am getting a proper response from the server. 
 But one small thing, if I look in the terminal window I am getting an error when using the example
```
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/home/will/Development/workspaces/oss/dinoloop/examples/parse_api/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/will/Development/workspaces/oss/dinoloop/examples/parse_api/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/home/will/Development/workspaces/oss/dinoloop/examples/parse_api/node_modules/express/lib/response.js:267:15)
    at ServerParseErrorMiddleware.invoke (/home/will/Development/workspaces/oss/dinoloop/examples/parse_api/dist/examples/parse_api/src/app/middlewares/filters.js:22:18)
    at /home/will/Development/workspaces/oss/dinoloop/examples/parse_api/dist/src/modules/core/dino.container.js:167:20
    at Layer.handle_error (/home/will/Development/workspaces/oss/dinoloop/examples/parse_api/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/will/Development/workspaces/oss/dinoloop/examples/parse_api/node_modules/express/lib/router/index.js:315:13)
    at /home/will/Development/workspaces/oss/dinoloop/examples/parse_api/node_modules/express/lib/router/index.js:284:7
```

**Comment by TheWillG** [comment]
One more small observation I made, inside `src/api/dino.ts` the constructor is this:
```
constructor(app: Express, baseUri: string) {
        this.appContainer = AppContainer.create(app);
        this.appContainer.baseUri = baseUri;
        this.appContainer.routeNotFoundMiddleware = RouteNotFoundMiddleware;
    }
```
When correct me if I am wrong, but I believe it should be `app: express.Application`. Please see example here for importing Express into app..... https://dev.to/briandgls/using-typescript-with-express--e0k
It looks like with Typescript you can import via `import * as express from 'express'` and then when you create a new app it is of type `const app: Express.Application = express();`

**Comment by ParallelTask** [comment]
Found the issue 

_examples/parse_api/src/app/middlewares/filters.ts: line-10_
```
{
if (err instanceof ParseParamException) next(err);
response.json(`${err.message} - Ended by Server level middleware`);
}
```
Invoking next would not stop express right away from current execution. So we need to wrap it inside else block to solve this
```
if (err instanceof ParseParamException) next(err);
else {
response.json(`${err.message} - Ended by Server level middleware`);
}
```

**Review by TheWillG — APPROVED** [review]
Looks good

**Pull request merged**
